sudo: false
language: node_js
node_js:
  - "5"

cache:
  directories:
    - node_modules

install:
  - npm install lerna@^2.0.0-beta typings -g
  - lerna bootstrap
  - lerna exec -- typings install
  - npm install

script:
  - npm run test
