
export const TOGGLE_SIDEBAR = 'app/TOGGLE_SIDEBAR'
export const TOGGLE_DARK_MODE = 'app/TOGGLE_DARK_MODE'
export const TOGGLE_SETTINGS_DIALOG_OPEN = 'app/TOGGLE_SETTINGS_DIALOG_OPEN'

// Tasks
export const FETCH_TASKS = 'tasks/FETCH_TASKS'
export const FETCH_TASKS_START = 'tasks/FETCH_TASKS_START'
export const FETCH_TASKS_SUCCESS = 'tasks/FETCH_TASKS_SUCCESS'
